/*
 * This source file was generated by the Gradle 'init' task
 */

#include "QFin++.h"
#include <cassert>

int main() {
    QFin::Greeter greeter;
    assert(greeter.greeting().compare("Hello, World!") == 0);
    return 0;
}
