/*
 * This source file was generated by the Gradle 'init' task
 */

#include <iostream>
#include <stdlib.h>
#include "QFin++.h"

std::string QFin::Greeter::greeting() {
    return std::string("Hello, World!");
}
